#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
resName="showrbq"
versionFile=/etc/opt/ss5/version.txt

checkup(){
    newVersion=`curl -s -L  https://raw.githubusercontent.com/${resName}/Socks5/master/version.txt`
    oldVersion=`cat $versionFile`
    if [ $newVersion = $oldVersion ] ;then
    echo "V"${oldVersion}
    else
    echo "New Version Found: V"$newVersion
    fi
}
clear

echo -e "SOCKS5 \033[32m$(checkup)\033[0m\n"
echo "1.Service Control"
echo "2.User Setting"
echo "0.Exit"
while :; do echo
	read -p "Enter: " choice
	if [[ ! $choice =~ ^[0-2]$ ]]; then
		echo "Unknown choice!"
	else
		break
	fi
done

if [[ $choice == 0 ]];then
	exit 0
fi
if [[ $choice == 1 ]];then
	clear
	bash /etc/opt/ss5/service.sh
fi
if [[ $choice == 2 ]];then
	clear
	bash /etc/opt/ss5/user.sh
fi
